service: earth-survey-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'eu-north-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - arn:aws:s3:::${env:S3_THUMB_BUCKET_NAME}/*
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    NODE_ENV: production
    FRONTEND_URL: ${env:FRONTEND_URL}
    SENTINEL_HUB_CLIENT_ID: ${env:SENTINEL_HUB_CLIENT_ID}
    SENTINEL_HUB_CLIENT_SECRET: ${env:SENTINEL_HUB_CLIENT_SECRET}
    SENTINEL_HUB_INSTANCE_ID: ${env:SENTINEL_HUB_INSTANCE_ID}
    S3_THUMB_BUCKET_NAME: ${env:S3_THUMB_BUCKET_NAME}
    CLOUDFRONT_DOMAIN: ${env:CLOUDFRONT_DOMAIN}

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi: '*' # API Gateway v2 (HTTP API) - more cost effective

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

package:
  patterns:
    - '!node_modules/aws-sdk/**'
    - '!**/*.md'
    - '!**/*.txt'
    - '!.env*'
